import type { SearchEntry } from "./types";

export const searchIndex: SearchEntry[] = [
  {
    id: "home",
    title: "Home",
    description: "OM Manual dashboard and quick navigation",
    href: "/",
    section: "Home",
    keywords: ["home", "dashboard", "start", "om"],
  },
  {
    id: "welcome",
    title: "Welcome to OM",
    description: "Introduction for new Online Managers",
    href: "/getting-started/welcome",
    section: "Getting Started",
    keywords: ["welcome", "getting started", "new om", "onboard"],
  },
  {
    id: "what-is-om",
    title: "What is an Online Manager?",
    description: "Role overview and expectations",
    href: "/getting-started/what-is-om",
    section: "Getting Started",
    keywords: ["online manager", "role", "om"],
  },
  {
    id: "responsibilities",
    title: "OM Responsibilities",
    description: "Core duties of Online Managers",
    href: "/getting-started/responsibilities",
    section: "Getting Started",
    keywords: ["responsibilities", "duties", "tasks"],
  },
  {
    id: "team-structure",
    title: "OM Team Structure",
    description: "How the OM team is organized",
    href: "/getting-started/team-structure",
    section: "Getting Started",
    keywords: ["team", "structure", "head"],
  },
  {
    id: "overall-workflow",
    title: "Overall Workflow",
    description: "End-to-end production and publishing flow",
    href: "/workflow/overall",
    section: "Workflow",
    keywords: ["workflow", "plan", "produce", "publish"],
  },
  {
    id: "production-workflow",
    title: "Production Workflow",
    description: "How content moves through departments",
    href: "/workflow/production",
    section: "Workflow",
    keywords: ["production", "departments", "content"],
  },
  {
    id: "clickup-messenger",
    title: "ClickUp → Messenger Workflow",
    description: "ClickUp first, Messenger second principle",
    href: "/workflow/clickup-messenger",
    section: "Workflow",
    keywords: ["clickup", "messenger", "production gc", "gc"],
  },
  {
    id: "publishing-workflow",
    title: "Publishing Workflow",
    description: "From approved content to published post",
    href: "/workflow/publishing",
    section: "Workflow",
    keywords: ["publishing", "schedule", "post"],
  },
  {
    id: "troubleshooting",
    title: "What To Do If...",
    description: "Troubleshooting guide for common OM situations",
    href: "/workflow/troubleshooting",
    section: "Workflow",
    keywords: ["troubleshooting", "help", "wrong", "unsure", "mistake"],
  },
  {
    id: "clickup-overview",
    title: "ClickUp Overview",
    description: "ClickUp is the source of truth for production",
    href: "/clickup/overview",
    section: "ClickUp",
    keywords: ["clickup", "overview", "source of truth"],
  },
  {
    id: "project-structure",
    title: "ClickUp Project Structure",
    description: "How projects and lists are organized",
    href: "/clickup/project-structure",
    section: "ClickUp",
    keywords: ["clickup", "project", "structure", "lists"],
  },
  {
    id: "tasks",
    title: "ClickUp Tasks",
    description: "Understanding production tasks",
    href: "/clickup/tasks",
    section: "ClickUp",
    keywords: ["clickup", "tasks", "task"],
  },
  {
    id: "assignees",
    title: "Assignee Field",
    description: "How members are assigned to tasks",
    href: "/clickup/assignees",
    section: "ClickUp",
    keywords: ["assignee", "assignment", "member", "head"],
  },
  {
    id: "due-dates",
    title: "Due Dates",
    description: "Target publishing dates and deadline monitoring",
    href: "/clickup/due-dates",
    section: "ClickUp",
    keywords: ["due date", "deadline", "overdue", "due soon"],
  },
  {
    id: "priority",
    title: "Priority",
    description: "Task priority levels in ClickUp",
    href: "/clickup/priority",
    section: "ClickUp",
    keywords: ["priority", "urgent", "clickup"],
  },
  {
    id: "statuses",
    title: "Task Status",
    description: "Status flow from To Do to Published",
    href: "/clickup/statuses",
    section: "ClickUp",
    keywords: ["status", "to do", "in progress", "ready to publish"],
  },
  {
    id: "task-comments",
    title: "Task Comments",
    description: "Submitting outputs and updates in comments",
    href: "/clickup/task-comments",
    section: "ClickUp",
    keywords: ["comments", "output", "submit", "caption"],
  },
  {
    id: "submitting-outputs",
    title: "Submitting Outputs",
    description: "How to properly submit finished work",
    href: "/clickup/submitting-outputs",
    section: "ClickUp",
    keywords: ["submit", "output", "attachment", "upload"],
  },
  {
    id: "om-monitoring",
    title: "OM Monitoring",
    description: "How OMs monitor ClickUp tasks",
    href: "/clickup/om-monitoring",
    section: "ClickUp",
    keywords: ["monitor", "monitoring", "follow up", "clickup"],
  },
  {
    id: "meta-overview",
    title: "Meta Business Suite Overview",
    description: "Where approved content becomes published content",
    href: "/meta/overview",
    section: "Meta Business Suite",
    keywords: ["meta", "business suite", "overview"],
  },
  {
    id: "scheduling",
    title: "Scheduling Posts",
    description: "Step-by-step scheduling workflow",
    href: "/meta/scheduling",
    section: "Meta Business Suite",
    keywords: ["schedule", "scheduling", "meta", "planner"],
  },
  {
    id: "meta-publishing",
    title: "Publishing Posts",
    description: "Publishing approved content on Meta",
    href: "/meta/publishing",
    section: "Meta Business Suite",
    keywords: ["publish", "publishing", "meta", "post"],
  },
  {
    id: "content-planner",
    title: "Content Planner",
    description: "View and manage scheduled content",
    href: "/meta/content-planner",
    section: "Meta Business Suite",
    keywords: ["content planner", "calendar", "schedule"],
  },
  {
    id: "meta-notifications",
    title: "Meta Notifications",
    description: "Managing Meta Business Suite notifications",
    href: "/meta/notifications",
    section: "Meta Business Suite",
    keywords: ["notifications", "alerts", "meta"],
  },
  {
    id: "meta-comments",
    title: "Meta Comments",
    description: "Managing comments on Facebook and Instagram",
    href: "/meta/comments",
    section: "Meta Business Suite",
    keywords: ["comments", "meta", "respond"],
  },
  {
    id: "meta-messages",
    title: "Meta Messages",
    description: "Handling messages through Meta Business Suite",
    href: "/meta/messages",
    section: "Meta Business Suite",
    keywords: ["messages", "dm", "inbox", "meta"],
  },
  {
    id: "meta-analytics",
    title: "Basic Analytics",
    description: "Insights available in Meta Business Suite",
    href: "/meta/analytics",
    section: "Meta Business Suite",
    keywords: ["analytics", "insights", "meta", "performance"],
  },
  {
    id: "facebook",
    title: "Facebook Page Guide",
    description: "Navigating SAS Bulletin on Facebook",
    href: "/social/facebook",
    section: "Social Media",
    keywords: ["facebook", "page", "posts"],
  },
  {
    id: "instagram",
    title: "Instagram Page Guide",
    description: "Navigating SAS Bulletin on Instagram",
    href: "/social/instagram",
    section: "Social Media",
    keywords: ["instagram", "reels", "feed", "stories"],
  },
  {
    id: "posting-guidelines",
    title: "Posting Guidelines",
    description: "Guidelines for publishing on social media",
    href: "/social/posting-guidelines",
    section: "Social Media",
    keywords: ["posting", "guidelines", "social media"],
  },
  {
    id: "community-management",
    title: "Community Management",
    description: "Managing the SAS Bulletin online community",
    href: "/social/community-management",
    section: "Social Media",
    keywords: ["community", "management", "audience"],
  },
  {
    id: "responding",
    title: "Responding to Users",
    description: "How to respond professionally to users",
    href: "/social/responding",
    section: "Social Media",
    keywords: ["responding", "users", "comments", "messages", "reply"],
  },
  {
    id: "escalation",
    title: "Escalation",
    description: "When and how to escalate issues",
    href: "/social/escalation",
    section: "Social Media",
    keywords: ["escalation", "escalate", "sensitive"],
  },
  {
    id: "assigning-oms",
    title: "Assigning OMs",
    description: "How publishing tasks are assigned to OMs",
    href: "/task-designation/assigning-oms",
    section: "Task Designation",
    keywords: ["assign", "om", "designation"],
  },
  {
    id: "publishing-responsibilities",
    title: "Publishing Responsibilities",
    description: "One post, one assigned OM principle",
    href: "/task-designation/publishing-responsibilities",
    section: "Task Designation",
    keywords: ["publishing", "responsibilities", "assigned om"],
  },
  {
    id: "availability",
    title: "Availability",
    description: "Managing OM availability for publishing",
    href: "/task-designation/availability",
    section: "Task Designation",
    keywords: ["availability", "unavailable", "handoff"],
  },
  {
    id: "avoiding-duplicates",
    title: "Avoiding Duplicate Work",
    description: "Prevent two OMs from publishing the same content",
    href: "/task-designation/avoiding-duplicates",
    section: "Task Designation",
    keywords: ["duplicate", "coordination", "same post"],
  },
  {
    id: "follow-ups",
    title: "Follow Up Early",
    description: "Timeline for proactive task follow-ups",
    href: "/task-designation/follow-ups",
    section: "Task Designation",
    keywords: ["follow up", "deadline", "monitor", "timeline"],
  },
  {
    id: "monthly-analytics",
    title: "Monthly Analytics",
    description: "Monthly social media performance review",
    href: "/analytics/monthly",
    section: "Analytics",
    keywords: ["analytics", "monthly", "review", "performance"],
  },
  {
    id: "what-to-monitor",
    title: "What to Monitor",
    description: "Metrics and signals to watch each month",
    href: "/analytics/what-to-monitor",
    section: "Analytics",
    keywords: ["monitor", "metrics", "reach", "engagement"],
  },
  {
    id: "key-metrics",
    title: "Key Metrics",
    description: "Important analytics metrics for OMs",
    href: "/analytics/key-metrics",
    section: "Analytics",
    keywords: ["key metrics", "reach", "engagement", "followers"],
  },
  {
    id: "monthly-review",
    title: "Monthly Review",
    description: "Analytics dashboard and review questions",
    href: "/analytics/monthly-review",
    section: "Analytics",
    keywords: ["monthly review", "dashboard", "learned", "improve"],
  },
  {
    id: "cheat-sheet",
    title: "OM Cheat Sheet",
    description: "Quick-reference checklist for OMs",
    href: "/quick-reference/cheat-sheet",
    section: "Quick Reference",
    keywords: ["cheat sheet", "quick reference", "checklist"],
  },
  {
    id: "before-publishing",
    title: "Before Publishing",
    description: "Pre-publish checklist",
    href: "/quick-reference/before-publishing",
    section: "Quick Reference",
    keywords: ["before publishing", "checklist", "clickup", "caption"],
  },
  {
    id: "after-publishing",
    title: "After Publishing",
    description: "Post-publish checklist",
    href: "/quick-reference/after-publishing",
    section: "Quick Reference",
    keywords: ["after publishing", "monitor", "update clickup"],
  },
  {
    id: "if-something-goes-wrong",
    title: "If Something Goes Wrong",
    description: "Stop, verify, ask, fix, document",
    href: "/quick-reference/if-something-goes-wrong",
    section: "Quick Reference",
    keywords: ["wrong", "mistake", "error", "fix"],
  },
  {
    id: "if-unsure",
    title: "If You're Unsure",
    description: "Ask first, don't guess",
    href: "/quick-reference/if-unsure",
    section: "Quick Reference",
    keywords: ["unsure", "help", "ask", "guess"],
  },
  {
    id: "resources",
    title: "Resources & Important Links",
    description: "Google Drive, ClickUp, Meta, and social links",
    href: "/resources",
    section: "Resources",
    keywords: ["resources", "links", "google drive", "clickup"],
  },
  {
    id: "production-gc",
    title: "Production GC",
    description: "SAS Bulletin Production Updates group chat",
    href: "/workflow/clickup-messenger",
    section: "Workflow",
    keywords: ["production gc", "messenger", "group chat", "updates"],
  },
];

export function searchEntries(query: string): SearchEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return searchIndex.slice(0, 8);

  return searchIndex
    .map((entry) => {
      let score = 0;
      if (entry.title.toLowerCase().includes(q)) score += 10;
      if (entry.description.toLowerCase().includes(q)) score += 5;
      if (entry.section.toLowerCase().includes(q)) score += 3;
      entry.keywords.forEach((kw) => {
        if (kw.includes(q) || q.includes(kw)) score += 4;
        if (kw.startsWith(q)) score += 2;
      });
      return { entry, score };
    })
    .filter(({ score }) => score > 0)
    .sort((a, b) => b.score - a.score)
    .map(({ entry }) => entry)
    .slice(0, 12);
}
